num2words/lang_ES.py

This commit adds correct ordinal numbers for spanish up to 10e18 - 1.

Updated spanish translations

---

num2words/__init__.py
num2words/lang_PL.py

I based the code on the Latvian version. Tested using the same set of tests - seems fine. Let me know if anything else needs to be done.

Added Polish language support

---

README.rst
num2words/__init__.py
num2words/lang_DK.py

Danish is very particular about word splits, endings, and contractions.

Danish language support

---

README.rst
num2words/__init__.py
num2words/base.py
num2words/lang_PT_BR.py
tests/test_pt_BR.py

This one adds support to Brazilian Portuguese language (maybe Portuguese itself, but I would need a reviewer from Portugal to ensure everything is the same).
I've implemented some tests as well. Please check it out.
If something is missing, please let me know.

Add support to pt_BR language

---

num2words/lang_RU.py

Translating negative integers was not supported (i.e ValueError), so I added some!

added support for negative integers for Russian language

---

num2words/lang_DE.py

See https://github.com/savoirfairelinux/num2words/pull/45
I hope I have done the tasks.

Translation of error messages

---

num2words/__init__.py
num2words/lang_IT.py
tests/test_it.py

As discussed with same license as other part of the project.

Italian support

---

num2words/__init__.py
num2words/lang_VN.py
tests/test_vn.py

[ADD] support VietNam

---

setup.py

This will populate the lower left of https://pypi.org/project/num2words

classifiers=CLASSIFIERS

---

README.rst

The list of languages and the briefness of introduction paragraph is quite important so they are corrected.

readme corrected

---

num2words/lang_DK.py

if you not install num2words via pip, lang_DK try to import num2words and it fails

lang_DK do not depends on num2words

---

num2words/__init__.py

There are at least two issues related to questions about how to use other converters.
This changes should allow the use of this converters

Allow call to other convertes as to_currency, to_year

---

num2words/__init__.py

This allows passing kwargs down to converters.

Pass kwargs to converters.

---

num2words/currency.py
num2words/lang_LT.py
num2words/lang_LV.py
num2words/lang_PL.py
num2words/lang_RU.py
num2words/lang_UK.py
tests/test_currency.py
tests/test_lv.py
tests/test_ru.py
tests/test_uk.py

Refactor and fix some issues with to_currency. Reduce code duplication.

---

num2words/lang_LV.py
tests/test_lv.py

Fixes some bugs, new currencies, closes #107

Improve lv

---

README.rst
num2words/__init__.py
num2words/base.py
num2words/lang_ES.py
num2words/lang_ES_CO.py
num2words/lang_ES_VE.py
setup.py
tests/test_de.py
tests/test_en.py
tests/test_es.py
tests/test_es_co.py
tests/test_es_ve.py
tests/test_nl.py
tests/test_pt_BR.py
tests/test_sl.py

Fix bugs in the float precision and the currency, increase test coverage

---

num2words/lang_FR.py
num2words/lang_FR_CH.py
num2words/lang_FR_DZ.py
tests/test_fr.py
tests/test_fr_ch.py
tests/test_fr_dz.py

* Fix issues  #116 #121 #127
*Review the code changes to check the new tests added and verify that all tests pass in Travis-CI.*

Increase test coverage for lang fr*

---

README.rst
num2words/__init__.py
num2words/base.py
num2words/currency.py
num2words/lang_HE.py
num2words/lang_LT.py
num2words/lang_LV.py
num2words/lang_PL.py
num2words/lang_RU.py
num2words/lang_TH.py
num2words/lang_UK.py
num2words/utils.py
tests/test_currency.py
tests/test_th.py
tests/test_utils.py

* add Thai Language from Thailand

add Thai Language from Thailand

---

.gitignore
README.rst
num2words/__init__.py
num2words/lang_FR_BE.py
tests/test_fr_be.py

* Add conversion to Belgium French (fr_BE) + related tests
- [] HOLD
Just use the normal command with the parameter `lang='fr_BE'`
NA

[ADD] Add lang fr_BE + tests

---

README.rst

* Supperted
* Supported
- [X ] READY

Typo correction in documentation

---

README.rst
num2words/__init__.py
num2words/lang_CZ.py
tests/test_cz.py

* Added Czech to readme.
* Added Czech language to tests.
As you requested, I added Czech to readme and I have created tests for Czech language.

Created translation to Czech language

---

CHANGES.rst
setup.py

Release preparation ...
Depend on #174

Release 0.5.7

---

num2words/base.py
num2words/lang_NL.py
tests/test_base.py
tests/test_nl.py

This is attempt at #159. It's very naive and only works for EUR but it's better than nothing.

Very naive to_currency implementation for NL

---

tests/test_en.py

Add tests for lang_EN ordinal coversion

---

num2words/lang_RU.py
tests/test_ru.py

* Implemented to_ordinal for RU
* Added test cases for this
Just run tests

Implemented to_ordinal for RU

---

CHANGES.rst
bin/num2words

Hey, it's a good time to make a new release, what do you think guys?

Release 0.5.8

---

CHANGES.rst
bin/num2words

Version 0.5.10 -- 2019/05/12
----------------------------
* Add Kannada language localization (#243)
* Revert some copyrights changed by mistake (#254)
* Add indian rupee to the supported currencies (#248)
* Improve currency functions for German and French (#247)
* Improve Slovene localization (#246)
* Improve Spanish localization (#240)
* Fix typo 'seperator' on source code (#238)
* Convert string to decimal values (#223)
* Improve German localization and test coverage (#237)
* Improve Polish localization (#233)
* Fix ordinal number for French ending on 1 (#236)

Release v0.5.10

---

.gitignore

Signed-off-by: William José Moreno Reyes <williamjmorenor@gmail.com>
Update .gitignore file

Update .gitignore to add .eggs/ directory

---

num2words/lang_ES.py
tests/test_es.py

* Add testcase
Output verified against num2words and double-checked for accuracy, coverage report shows increase.
No other notes

Add ordinal 12,345 to ES test suite to increase coverage

---

tests/test_en.py

* Add testcase for ordinal not ending in 'y'
Full line/branch coverage of file.

Add testcase for lang_EN.py

---

README.rst
num2words/__init__.py
num2words/lang_KZ.py
tests/test_kz.py

* Add support of Kazakh language (KZ)
All changes are covered by tests in test_kz.py module.

Add support of Kazakh language (KZ)

---

README.rst
num2words/__init__.py
num2words/lang_EU.py
num2words/lang_HU.py
tests/test_hu.py

* Added support for Hungarian language.
run num2words with `lang='hu'`
--

Added support for Hungarian language

---

README.rst

[UPD] Readme file

---

num2words/lang_PL.py
tests/test_pl.py

* added support for polish ordinal numbers
*unit tests cover all of the possible cases*
*-*

Polishordinals

---

tests/test_base.py

* ...
* ...
Added a new check to fix test coverage

Add new check to base

---

CHANGES.rst
bin/num2words

new release

---

num2words/lang_IT.py
tests/test_it.py

Fix #508: Handle string inputs in Italian `to_ordinal`

---

num2words/__init__.py
num2words/lang_SK.py
tests/test_sk.py

--
Run tests. Optionally check manually.
Added missing Slovak language support. Based on Czech module due to language similarity.

Add Slovak language support

---

.gitignore
README.rst
num2words/__init__.py
num2words/lang_ES_CR.py
tests/test_es_cr.py

Changes proposed in this pull request:
Spanish Costa Rica Language added
Status
READY
How to verify this change
Similar language as Spanish Colombia
Additional notes
Small change in .gitignore file for build artifacts and IDE files

[ADD] num2words: es_CR language added

---

tests/test_base.py
tests/test_dk.py

Add test to improve coverage

---

num2words/__init__.py
num2words/lang_DA.py
tests/test_da.py

* Switch danish language code to ISO standard 'da'
- [X ] READY

Change danish language code to DA

---

.github/workflows/ci.yml
setup.py
tox.ini

Updated python versions, removed 3.7 and added 3.13

---

num2words/README.md

Fix formatting in README.md
