savoirfairelinux/num2words

num2words/lang_DE.py

See: https://de.wiktionary.org/wiki/tausend

Fix spelling error of German number tausend (1000)

---

num2words/__init__.py
num2words/lang_FR_CH.py
tests/test_fr_ch.py

French-speaking Switzerland use slightly different words for 70, 80 and 90, so I added a derivative language named fr_CH to support those.

Add Swiss-French variants of numbers between 60 and 100.

---

num2words/lang_PT_BR.py
tests/test_pt_BR.py

Hi
In Brazilian Portuguese we use comma as decimal sign instead dot. Ex.: we use 1,01 instead 1.01. So in the text the correct word is 'vírgula'( comma ) 
Thank you for great work

In Brazilian Portuguese the decimal sign is comma ',' 

---

num2words/base.py
num2words/lang_DE.py
tests/test_de.py

I am not a German native. But I'm quite sure about the correction I've made.
1. using '.' instead of 'te' as suffix of ordinal number. ex: 23.
2. normally, German use 'en' instead of 'es' for the plural of 'million' so it becomes 'millionen'
3. Ordinal form of number 100, 1000 and so on, it adds 'ste' instead of only 'te'. example: hundertste, tausendste ...
However it needs to be verified.

correction on lang_DE: ordnum, plural and ord form of >= 10**6

---

num2words/lang_IT.py
tests/test_it.py

What I did:
- A complete rewrite; the logic is somewhat easier to follow and the code pretty much follows the standard style guidelines.
- More tests.
- Implement the converter for floating point values too.
~Still, TODO~ **Done!:**
- Accents on composite words of "tre" ("ventitré", "centotré", ecc.).
- Commas for numbers larger than `10^30` (i.e. a "quadriliardo").

Improvements, corrections, and bug fixes for the `lang_IT` module.

---

README.rst
num2words/__init__.py
num2words/lang_AR.py
tests/test_ar.py

Add Arabic support:
```
>>> from num2words import num2words
>>> num2words(42, lang="ar")
'اثنين وأربعين'
>>> 
```

Support Arabic

---

num2words/lang_LV.py
num2words/lang_PL.py
num2words/lang_RU.py
num2words/lang_UK.py

Expose `to_currency` where possible.
Did not move existing functions onto converters to prevent API breakage.

Expose to to_currency.

---

num2words/lang_IT.py
tests/test_it.py

lang_IT was not detecting floats properly:
```
In [5]: num2words.num2words(4800.0, lang='it')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9e492d6f2391> in <module>()
----> 1 num2words.num2words(4800.0, lang='it')
/usr/local/lib/python2.7/dist-packages/num2words/__init__.pyc in num2words(number, ordinal, lang, to, **kwargs)
90         raise NotImplementedError()
91 
---> 92     return getattr(converter, 'to_{}'.format(to))(number, **kwargs)
/usr/local/lib/python2.7/dist-packages/num2words/lang_IT.pyc in to_cardinal(self, number)
179             string = self.hundreds_to_cardinal(number)
180         elif number < 1000000:
--> 181             string = …
```

Fix lang_IT handling of floats

---

num2words/lang_EN.py
tests/test_en.py

* Rework lang_EN.to_year() to account for canonical year pronunciations ("twenty seventeen", etc.).
* Add unit tests for the same.

lang_EN.to_year(): render correct pronunciations

---

README.rst

* Fix "Usage": "cardinal" => "ordinal".
```
>>> num2words(42,to='cardinal')
u'forty-two'
>>> num2words(42,to='ordinal')
u'forty-second'
```
* Add PyPI shield. Closes #36.
* Fix link to GitHub.

Improve README.rst.

---

num2words/lang_ES.py
tests/test_es.py

* Update es_ES to new implementation of the to_currency()
* Change some spanish translations (in spanish 'cent' isn't 'centavos' is 'centimos' and the old currency is 'pesetas' not 'pesos')
`import num2words`
`a = 1234.01`
`print num2words.num2words(a, to='currency', lang='es_ES')`
`mil doscientos treinta y cuatro euros con un centimo`

Change implementation of to_currency() in es_ES

---

num2words/base.py
num2words/lang_LT.py
num2words/lang_LV.py
tests/test_lt.py
tests/test_lv.py

Negative amounts were not working (when no currency is used), because
`get_digits` method does not expect `-` sign, which crashes conversion.
To avoid that, we split minus sign from number string and prepare its
word to be used with amount words.
closes: #184
Negative amounts for LT and LV conversion was not implemented and was crashing the conversion, so fix was committed (look for above for description).
Unittests for LT and LV were added to verify this change that it works with negative amounts (when currency is not used).

[FIX] lang_LT, lang_LV: negative amounts

---

.coveragerc
MANIFEST.in
README.rst
bin/num2words
requirements-test.txt
setup.py
tests/test_cli.py
tox.ini

* Add a command line tool to use num2words
```
Usage:
num2words [options] <number>
num2words --list-languages
num2words --list-converters
num2words --help
Arguments:
<number>                Number you want to convert into words
Options:
-L --list-languages     Show all languages.
-C --list-converters    Show all converters.
-l --lang=<lang>        Output language [default: en].
-t --to=<to>            Output converter [default: cardinal].
-h --help               Show this message.
-v --version            Show version.
Examples:
$ num2words 10001
ten thousand and one
$ num2words 10123123 --lang es
diez millones ciento veintitrés mil ciento veintitrés
$ num2words 24,120.10
twenty-four thousand, one hundred and twenty point one
$ num2words 24,120.10 -l es
veinticuatro mil ciento veinte punto …
```

Add a command line tool to use num2words, credits to @hernamesbarbara

---

num2words/lang_FR.py
tests/test_fr.py

* `num2words(1.5, lang='fr', to='currency')` now returns `'un euro et cinquante centimes'` instead of `'un euro et cinq centimes'`
`num2words(1.5, lang='fr', to='currency')`

[FIX] lang_FR: Fixed decimal handling in french currency

---

num2words/lang_DE.py
tests/test_de.py

* Added more test to tests/test_de.py for lang_DE.py
Running coverage tools should indicate a higher coverage on lang_DE.py
These changes also unveil a few (probably unknown) inconsistencies regarding num2years in german:
Before the year 2000 the years have a lot of spaces in them, while afterwards they are one word.

added more tests to lang_DE.py

---

num2words/lang_ES.py
tests/test_es.py

add currency PEN in es lang
* add PEN currency (soles, centimos)
```
num2words(42.5, lang='es', to='currency', currency='PEN')
cuarenta y dos soles con cincuenta céntimos
```

add currency PEN

---

num2words/lang_DE.py
tests/test_de.py

The ordinals for very big numbers (million and up) were incorrect.
For the german speakers:
Incorrect (old): Millionenste / Billiardenste
Correct (new): Millionste / Billardste

Correction of german ordinals.

---

.coveragerc
.travis.yml
README.rst
num2words/lang_PT.py
num2words/lang_PT_BR.py
requirements-test.txt
tests/test_fi.py
tox.ini

Overall goals were to only runs flake8 and isort once (via tox or travis), increase breadth of coverage information (branching and tests run), and add Python 3.7 testing.
* Include branch coverage in coverage reports
* Run coverage against tests and main package, ignoring other directories
* Add Flake8 and isort sections to run only once (under CPython 3.6)
* Add CPython 3.7 to testing matrix (requires Xenial with sudo)
* Only submit coverage statistics if results file exists (specifically to exclude flake8 and isort)
* Remove unused test generation code from test_fi.py
* Add python3.7 to tox execution list
* Move flake8 and isort into separate execution sections for tox
* Include specific dependencies for each testenv
* Add coverage report requiring 100% coverage of test code to ensure …

Refactor testing setup

---

num2words/lang_CZ.py
num2words/lang_HE.py
num2words/lang_LT.py
num2words/lang_LV.py
num2words/lang_PL.py
num2words/lang_RU.py
num2words/lang_UK.py
tests/test_lt.py
tests/test_lv.py
tests/test_pl.py

- typos in Polish names of 900 ("dziewięćset") and 10**27 (long scale - "kwadryliard")
- expanded PL names up to decilliard (10**63 - long scale,)
- words for power of thousand are no longer inserted if said power is 0 (e.g. in Polish: 1_000_000_000 => "miliard", not "miliard milionów tysięcy").
Names:
https://pl.wikipedia.org/wiki/Liczebniki_główne_potęg_tysiąca#Nazwy_utrwalone_w_piśmiennictwie

Extend Polish names + typos; power of thousand names not inserted when value is 0

---

CHANGES.rst
bin/num2words

I have made a pre-release, once this gets merged on master I will publish the new release on [github](https://github.com/savoirfairelinux/num2words/releases) and pypi you can test the pre-release uploaded on [test.pypi](https://test.pypi.org/project/num2words/).

Release 0.5.9

---

num2words/lang_DE.py
tests/test_de.py

* ordinals: "Million" etc. is written in upper case
* cardinals: similar rule for 1 million etc. as for 100, 1000
* cardinals: several millions etc. are written without space
* add some more tests
- [X ] READY
https://de.wikipedia.org/wiki/Million#Sprachliches

German improvements

---

num2words/__init__.py
num2words/base.py
tests/test_cli.py

* Punt string handling to python Decimal object, this correctly represents both integers and floats (except with regards to trailing zeros)
* num2words('1.00') == 'one' instead of 'one point zero zero'
* Change command line tests to reflect handling of ints
"bin/num2words 1" yields 'one' instead of 'one point zero'
all((num2words(i) == num2words(str(i)) for i in range(1000))) == True
String to Decimal conversion is available in the language converter object, I'm unsure if this will ever need to be adapted per language, and it seems ill-advised to guess based on current or target locale/language.
Python >= 3.5 can use underscores as thousands separators in strings i.e. num2words('3_000') = 'three thousand'

Convert strings to Decimal values

---

num2words/base.py
num2words/lang_ES.py
num2words/lang_FI.py
num2words/lang_HE.py
num2words/lang_JA.py
num2words/lang_KO.py
num2words/lang_PT.py
num2words/lang_SR.py
tests/test_cz.py
tests/test_en.py
tests/test_lv.py
tests/test_nl.py
tests/test_pl.py
tests/test_ru.py
tests/test_sr.py
tests/test_uk.py

Fix typo 'seperator' on source code

---

num2words/lang_AR.py
num2words/lang_ES.py
tests/test_cli.py
tests/test_es.py
tox.ini

* Fixes Spanish language
This is a cosmetic change: make sure that the accent in 'céntimos' is there when running num2words with `to='currency'`.

Updates accents on céntimos in Spanish

---

num2words/lang_DE.py
num2words/lang_FR.py
num2words/lang_FR_DZ.py
num2words/lang_NL.py
tests/test_de.py
tests/test_fr.py
tests/test_fr_be.py
tests/test_fr_ch.py
tests/test_fr_dz.py
tests/test_nl.py

by Sarah Beranek
* Adding CURRENCY_FORMS for German and French
* Replacing old currency functions with updated ones for German and French.
* Adding more CURRENCY_FORMS options for dutch
```
lang='de'                                                                                     
var1 = '49.95'                                                                                                                                 
var2 = '1.01'                                                                              
b = num2words(var1, lang=lang, to='currency', currency='USD')
print(b)                                                               
d = num2words(var2, lang=lang, to='currency', currency='EUR')
print(d) 
```
the same test for French with setting `lang='fr'` or Dutch with …

Fixing currency functions for german and french. Adding Currency_Forms for DE, FR and NL.

---

num2words/lang_EU.py

* Add support for the Indian rupee. 
`num2words('102541.34', to='currency', currency='INR', adjective=True)`
The standard currency code used internationally for the Indian Rupee is the INR. The added currency forms for the Indian Rupee are linked to the 'INR' code. The change is made in the Num2Word_EU class, where most of the currency forms seem to be. In principle, the provided forms are valid for English and similar languages.

Add support for the Indian rupee.

---

num2words/lang_IT.py
tests/test_tr.py

Commit 53b4518 made added explicit utf-8 encoding for all sources, among other things. A copyright notice in `tests/test_tr.py` was mistakenly removed and two were added in `num2words/lang_it.py`. I know this was a simple overlook, I just thought it would be best to explicitly give credit where credit is due.

Revert some copyright changes made in commit 53b4518

---

num2words/__init__.py
num2words/lang_ES_NI.py
tests/test_errors.py
tests/test_es_ni.py

Signed-off-by: William José Moreno Reyes <williamjmorenor@gmail.com>
modified:   num2words/__init__.py
new file:   num2words/lang_ES_NI.py
python bin/num2words 1 -l es_NI --to currency
un córdoba con cero centavos
python bin/num2words 1.02 -l es_NI --to currency
un córdoba con dos centavos
python bin/num2words 2.02 -l es_NI --to currency
dos córdobas con dos centavos
python bin/num2words 1.01 -l es_NI --to currency
un córdoba con un centavo
Please add support for Nicaragua Currency

Add es_NI currency

---

tests/test_dk.py

Work toward #109 
* Add tests for lang_DK.py
Increase present in coverage report
* The code DK seems to refer to the country of Denmark, not the language of Danish which has the locale abbreviation da (da_DK is also valid). Should this be updated as well?
* Further values seem incorrect from what I can quickly find online, I could use review or help from someone who knows more about the language.
num2words(1000, lang='dk', to='ordinal') == 'ettusindte'
num2words(12345, lang='dk', to='ordinal') == 'tolvtusinde og trehundrede og femogfyrre'
but what I can find shows the values should be 'et tusind' and 'tolv tusinde tre hundrede og femogfyrre' respectively. As I'm not sure which is correct (if not both), I don't want to add any failing test cases I can't validate.

Add simple tests for lang_DK.py

---

num2words/base.py
tests/test_base.py

Signed-off-by: William José Moreno Reyes <williamjmorenor@gmail.com>
Fixes: https://github.com/savoirfairelinux/num2words/issues/125
Just more tests to improve coverage.
This pull request update test coverage of num2words/base.py to 92%

Add more tests to base.py

---

num2words/lang_NL.py

Current output outputs essentially german style Ordinal numeric output (with the dot `.`)
This has been changed for the Dutch language to use `e` instead.
All numbers in Dutch use a `e` suffix for their ordinal numerical form.
So everywhere that had `.` needs to have `e`.
In Dutch we use `e` or with Unicode available either `ᴱ` or `ᵉ`.
So `1e`, `1ᴱ`, `1ᵉ` for example. For now I just put the standard `e` in there, but all could work.

Fix ordinal_num output for Dutch (NL)

---

README.rst
num2words/__init__.py
num2words/lang_AM.py
tests/test_am.py

Fix Amharic language support

---

num2words/lang_IT.py
tests/test_it.py

* Adding support for italian translation of some currencies (to_currency)
* Tests for italian language currencies
```
lang='it'                                                                                     
var1 = '49.95'                                                                                                                                 
var2 = '1.01'                                                                              
b = num2words(var1, lang=lang, to='currency', currency='USD')
print(b)                                                               
d = num2words(var2, lang=lang, to='currency', currency='EUR')
print(d) 
```

[ADD] num2words: add support to translate some currencies in italian language

---

num2words/lang_TR.py
tests/test_tr.py

#454 Negative Number return wrong text Fixes @emregeldegul
* -50 (cardinal) -> eksielli
* -3 (currency) -> eksiellilira
Add new cases in the turkish test for negative numbers
I opened a [PR](https://github.com/savoirfairelinux/num2words/pull/455) before but closed it because there were too many conflicts.

#454: [tr] fix negative number problem

---

num2words/lang_NO.py
tests/test_no.py

This may fix #110 but was not the motivation for the fix
* 'lang_NO.py':
* Removed hyphen between tens and units (e.g. `92` should convert to `nittito` not `nitti-to`)
* Fixed currency conversion (this was v broken)
* Corrected ordinal_num (looks like this had not been changed from copying English)
* removed comma from long word form numbers
* 'test_no.py':
* Created Norwegian test cases file with test cases
I have added hopefully quite comprehensive tests for the changes I have made and generally basic tests for Norwegian. Specific examples include:
```>>> from num2words import num2words
>>> num2words('92', lang='no')
'nittito'
>>> num2words('1345', lang='no')
'en tusen tre hundre og førtifem'
>>> num2words('5', lang='no', to='ordinal')
'femte'
>>> num2words('5', lang='no', …
```

Norwegian uplift

---

.github/workflows/ci.yml
setup.py
tox.ini

*  Removed python3.6 from testing because is deprecated in ubuntu 20.04
*  Added python 3.11
*  Set flake to fix version 5
- [x ] READY

Change python3.6 to python3.11 because deprecation in ubuntu 22.04

---

README.rst
num2words/__init__.py
num2words/lang_AZ.py
tests/test_az.py

* implemented all conversions for Azerbaijani language
* added tests for Azerbaijani language
*All new codes are validated by unit tests. For verifying translations any reliable translator service can be used.*
*No additional notes.*

add support for Azerbaijani language

---

num2words/lang_FA.py

* Changed the format of converting five numbers include (15, 16, 17, 18, 19)
By testing the num2words/lang_FA.py file and calling the 'cardinal3' function, when you should see the below result:
```
num2word_fa = Num2Word_FA()
number = int('۱۹')
modified_number = num2word_fa.cardinal3(number)
print(modified_number)
```
Before this change, the result was 'نه و ده' which is wrong.
Also for numbers ۱۵, ۱۶, ۱۷, ۱۸ it has to result in: 'هجده', 'هفده', 'شانزده', 'پانزده'
This problem was a little but impactful mistake in using the formal Persian language, not the informal one.

fix 15, 16, 17, 18, 19 issue

---

README.rst
num2words/__init__.py
num2words/lang_EN_NG.py
tests/test_en_ng.py

*So all that's required is to set the `lang` attribute to `en_NG`*
*Hopefully this would be merged into the main branch, when this is done, the language would be represented as en_NG (English - Nigeria)*

Added support for the Nigerian Naira

---

CHANGES.rst

Added changes for release 0.5.13

---

.github/workflows/ci.yml
setup.py
tox.ini

* Run tests against Python 3.12.
* Add trove classifier.
Run tox 
Python 3.12 is available since October 2, 2023, see https://blog.python.org/2023/10/python-3120-final-now-available.html.

Run tests against Python 3.12

---

README.rst
num2words/__init__.py
num2words/lang_BE.py
num2words/lang_EU.py
tests/test_be.py

ISO code for Belarusian language is be, not by.
- [X ] READY
https://lh.2xlibre.net/locale/be_BY/

[FIX] ISO code for Belarusian language is be, not by.

---

num2words/base.py
tests/test_am.py
tests/test_en.py
tests/test_en_ng.py
tests/test_hu.py
tests/test_nl.py

This is pulled over from @cheng-jess 's work [here](https://github.com/savoirfairelinux/num2words/pull/602); I only removed failing test cases which appear to have come from the author's other PR [here](https://github.com/savoirfairelinux/num2words/pull/598) by mistake.

Zero cents bug (fix for test cases in original PR)

---

num2words/lang_IT.py
tests/test_it.py

* Italian language: detect non-integer cardinals regardless of whether they are `float` or `Decimal` (they will be the latter if a string is passed to `num2words()` rather than a float)
* Add test for this case
Run tests

IT: support Decimal class

---

num2words/lang_ES.py
tests/test_es.py

It seems support for grammatical gender was planned but never implemented
* Adds support for feminine grammatical gender with keyword argument gender='f'
* Changes in ordinal spelling according to Real Academia Española (https://www.rae.es/ortografía/ortografía-de-los-numerales-ordinales)
I added test cases for feminine ordinals to test_es.py

Spanish: add support to grammatical gender / spelling

---

num2words/base.py
tests/test_en.py

Current behaviour
> num2words(-0.12, lang="en")
'zero point one two'
Expected behaviour
> num2words(-0.12, lang="en")
'minus zero point one two'

Fix negword before zero with floats
